# Generated by Django 5.2.7 on 2025-10-06 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_metodopago_options_alter_notificacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='suscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.suscripcion'),
        ),
    ]
